<script lang="ts">
	import Upload from '@lucide/svelte/icons/upload';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import Download from '@lucide/svelte/icons/download';
	import Eye from '@lucide/svelte/icons/eye';
	import Search from '@lucide/svelte/icons/search';
	import X from '@lucide/svelte/icons/x';
	import {
		Button,
		Badge,
		Card,
		CardContent,
		CardHeader,
		CardTitle,
		Alert,
		AlertDescription,
		AlertTitle,
		Input,
		Tabs,
		TabsList,
		TabsTrigger
	} from '@sden99/ui-components';
	import {
		DropdownMenu,
		DropdownMenuTrigger,
		DropdownMenuContent,
		DropdownMenuCheckboxItem
	} from '$lib/components/core/dropdown-menu';
	import ThemeToggle from '$lib/components/ThemeToggle.svelte';
	import ViewSwitcher from '$lib/components/layout/ViewSwitcher.svelte';
	import StorageBadge from '$lib/components/layout/StorageBadge.svelte';
	import FileUpload from '$lib/components/data/shared/FileUpload.svelte';
	import { ruleState } from '$lib/core/state/ruleState.svelte';
	import { validationService } from '$lib/services/validationService.svelte';
	import { cdiscEngineService } from '$lib/services/cdiscEngineService.svelte';
	import {
		exportRulesToYaml,
		exportRulesToJson,
		downloadFile
	} from '$lib/utils/ruleExporter';
	import { FileImportManager } from '$lib/core/services/FileImportManager';
	import { browser } from '$app/environment';
	import * as errorState from '$lib/core/state/errorState.svelte.ts';
	import * as appState from '$lib/core/state/appState.svelte.ts';
	import { selectDataset } from '$lib/core/actions/selectionAction';
	import { untrack } from 'svelte';
	import type { Rule } from '@sden99/validation-engine';

	let { data } = $props();

	// File manager for YAML rule uploads
	let fileManager = $state<FileImportManager | null>(null);

	if (browser && data?.initialData?.container) {
		fileManager = new FileImportManager(data.initialData.container, {
			onDatasetReady: () => validationService.revalidate()
		});
	}

	async function handleFileChangeEvent(event: Event) {
		if (!fileManager) {
			errorState.logWarning('File manager not available');
			return;
		}

		const files = (event.target as HTMLInputElement).files;
		if (!files?.length) return;

		const validFiles = Array.from(files).filter((file) => {
			const validation = fileManager!.validateFile(file);
			if (!validation.valid && validation.error) {
				errorState.logWarning(validation.error);
			}
			return validation.valid;
		});

		if (validFiles.length) {
			await Promise.allSettled(validFiles.map((file) => fileManager!.processFile(file)));
		}
	}

	// Rules state
	let importedRules = $derived(ruleState.rules);
	let autoRules = $derived(validationService.getAutoGeneratedRules());
	let engineRules = $derived(cdiscEngineService.getEngineRules());
	let warnings = $derived(ruleState.warnings);
	let showExportMenu = $state(false);
	let activeTab = $state('all');
	let ruleCount = $derived(ruleState.count);

	let allRules = $derived([...autoRules, ...importedRules, ...engineRules]);

	let engineLastRunLabel = $derived.by(() => {
		const ts = cdiscEngineService.lastRunAt;
		if (!ts) return null;
		return new Date(ts).toLocaleTimeString();
	});

	// Filter state with per-tab persistence
	let searchTerm = $state('');
	let selectedRuleTypes = $state<Set<string>>(new Set());
	let selectedDomains = $state<Set<string>>(new Set());
	let selectedTargetVars = $state<Set<string>>(new Set());
	let violationsOnly = $state(false);

	// Restore filters when tab changes (only tracks activeTab, not ruleFilters)
	$effect(() => {
		const tab = activeTab;
		untrack(() => {
			const filters = appState.getRuleTabFilters(tab);
			searchTerm = filters.searchTerm;
			selectedRuleTypes = new Set(filters.ruleTypes);
			selectedDomains = new Set(filters.domains);
			selectedTargetVars = new Set(filters.targetVars);
			violationsOnly = filters.violationsOnly;
		});
	});

	// Persist filters when they change
	$effect(() => {
		const snapshot = {
			searchTerm,
			ruleTypes: [...selectedRuleTypes],
			domains: [...selectedDomains],
			targetVars: [...selectedTargetVars],
			violationsOnly
		};
		untrack(() => appState.setRuleTabFilters(activeTab, snapshot));
	});

	// Tab-filtered rules (before additional filters)
	const tabFilteredRules = $derived.by(() => {
		if (activeTab === 'imported') return importedRules;
		if (activeTab === 'auto') return autoRules;
		if (activeTab === 'engine') return engineRules;
		return allRules;
	});

	// Unique filter options from tab-filtered rules
	const uniqueRuleTypes = $derived([...new Set(tabFilteredRules.map(r => r.Rule_Type))].sort());

	const uniqueDomains = $derived.by(() => {
		const domains = new Set<string>();
		for (const rule of tabFilteredRules) {
			rule.Scope?.Domains?.Include?.forEach((d: string) => { if (d !== 'ALL') domains.add(d); });
		}
		return [...domains].sort();
	});

	const uniqueTargetVars = $derived.by(() => {
		const vars = new Set<string>();
		for (const rule of tabFilteredRules) {
			if (rule.Target_Variable) vars.add(rule.Target_Variable);
		}
		return [...vars].sort();
	});

	// Apply all filters on top of tab-filtered rules
	let displayedRules = $derived.by(() => {
		let rules = tabFilteredRules;

		if (searchTerm.trim()) {
			const term = searchTerm.toLowerCase();
			rules = rules.filter(r =>
				r.Core.Id.toLowerCase().includes(term) ||
				r.Description.toLowerCase().includes(term) ||
				(r.Target_Variable?.toLowerCase().includes(term))
			);
		}
		if (selectedRuleTypes.size > 0)
			rules = rules.filter(r => selectedRuleTypes.has(r.Rule_Type));
		if (selectedDomains.size > 0)
			rules = rules.filter(r => {
				const inc = r.Scope?.Domains?.Include;
				if (!inc) return false;
				if (inc.includes('ALL')) return true;
				return inc.some((d: string) => selectedDomains.has(d));
			});
		if (selectedTargetVars.size > 0)
			rules = rules.filter(r => r.Target_Variable && selectedTargetVars.has(r.Target_Variable));
		if (violationsOnly)
			rules = rules.filter(r => violationsByRule.has(r.Core.Id));

		return rules;
	});

	// Filter helpers
	function toggleSetItem(set: Set<string>, item: string): Set<string> {
		const next = new Set(set);
		if (next.has(item)) next.delete(item); else next.add(item);
		return next;
	}

	function clearAllFilters() {
		searchTerm = '';
		selectedRuleTypes = new Set();
		selectedDomains = new Set();
		selectedTargetVars = new Set();
		violationsOnly = false;
	}

	const hasActiveFilters = $derived(
		searchTerm.trim() !== '' ||
		selectedRuleTypes.size > 0 ||
		selectedDomains.size > 0 ||
		selectedTargetVars.size > 0 ||
		violationsOnly
	);

	// Violation counts per rule (reactive — updates when validation results change)
	let violationsByRule = $derived.by(() => {
		const map = new Map<string, { totalIssues: number; datasets: string[] }>();
		for (const rule of allRules) {
			const violations = validationService.getViolationsByRule(rule.Core.Id);
			if (violations.length > 0) {
				const datasets = [...new Set(violations.map((v) => v.datasetId))];
				const totalIssues = violations.reduce((sum, v) => sum + v.issueCount, 0);
				map.set(rule.Core.Id, { totalIssues, datasets });
			}
		}
		return map;
	});

	function getRuleSource(rule: Rule): 'auto' | 'imported' | 'engine' {
		if (rule.Core.Id.startsWith('AUTO.')) return 'auto';
		if (rule.Core.Id.startsWith('ENGINE.')) return 'engine';
		return 'imported';
	}

	function isImported(rule: Rule): boolean {
		return getRuleSource(rule) === 'imported';
	}

	function handleDelete(ruleId: string) {
		ruleState.removeRule(ruleId);
		validationService.revalidate();
	}

	function handleClearImported() {
		ruleState.clearAll();
		validationService.revalidate();
	}

	function handleDismissWarnings() {
		ruleState.clearWarnings();
	}

	function handleExport(format: 'yaml' | 'json', scope: 'imported' | 'all') {
		const rulesToExport = scope === 'imported' ? importedRules : allRules;
		if (rulesToExport.length === 0) return;

		if (format === 'yaml') {
			const content = exportRulesToYaml(rulesToExport);
			downloadFile(content, `rules-${scope}.yaml`, 'text/yaml');
		} else {
			const content = exportRulesToJson(rulesToExport);
			downloadFile(content, `rules-${scope}.json`, 'application/json');
		}
		showExportMenu = false;
	}

	function handleViewViolations(ruleId: string) {
		const violations = validationService.getViolationsByRule(ruleId);
		if (violations.length === 0) return;

		// Select the first dataset that has violations for this rule
		const firstViolation = violations[0];
		selectDataset(firstViolation.datasetId);

		// Set pending filter so dataset detail page applies it once the table loads
		appState.pendingRuleFilter.value = ruleId;

		// Switch to dataset view
		appState.appView.value = 'datasets';
	}

	function getScopeDisplay(rule: Rule): string {
		const scope = rule.Scope;
		if (!scope?.Domains?.Include) return 'All domains';
		if (scope.Domains.Include.includes('ALL')) return 'All domains';
		return scope.Domains.Include.join(', ');
	}

	function getExecutabilityVariant(rule: Rule): 'default' | 'secondary' | 'outline' | 'destructive' {
		return rule.Executability === 'Fully Executable' ? 'default' : 'secondary';
	}
</script>

<div class="bg-background flex h-full flex-col">
	<!-- Navigation bar -->
	<header
		class="bg-muted/30 supports-[backdrop-filter]:bg-muted/30 dark:bg-background/95 dark:supports-[backdrop-filter]:bg-background/95 dark:border-border sticky top-0 z-50 w-full border-b backdrop-blur"
	>
		<div class="container flex h-14 max-w-none px-6">
			<div class="flex w-full items-center justify-between">
				<div class="flex items-center gap-4">
					<FileUpload {handleFileChangeEvent} accept=".yaml,.yml" />
				</div>

				<div class="absolute left-1/2 flex -translate-x-1/2 transform items-center gap-2">
					<h1 class="text-foreground text-xl font-semibold">Validation Rules</h1>
					{#if ruleCount > 0}
						<Badge variant="secondary">{ruleCount}</Badge>
					{/if}
				</div>

				<div class="text-foreground flex items-center gap-4">
					<StorageBadge />
					<ViewSwitcher />
					<ThemeToggle />
				</div>
			</div>
		</div>
	</header>

	<!-- Main content -->
	<div class="flex-1 overflow-auto">
		<div class="mx-auto max-w-4xl p-6">
			<!-- Warning banner -->
			{#if warnings.length > 0}
				<Alert class="mb-6">
					<AlertTitle>Import Warnings</AlertTitle>
					<AlertDescription>
						<ul class="mt-2 list-inside list-disc space-y-1 text-sm">
							{#each warnings as warning}
								<li>{warning}</li>
							{/each}
						</ul>
						<Button variant="ghost" size="sm" class="mt-2" onclick={handleDismissWarnings}>
							Dismiss
						</Button>
					</AlertDescription>
				</Alert>
			{/if}

			<!-- Header with actions -->
			<div class="mb-6 flex items-center justify-between">
				<div>
					<h2 class="text-foreground text-2xl font-bold">Validation Rules</h2>
					<p class="text-muted-foreground mt-1 text-sm">
						{allRules.length} total ({autoRules.length} auto-generated, {importedRules.length} imported{#if engineRules.length > 0}, {engineRules.length} engine{/if})
					</p>
				</div>

				<div class="flex items-center gap-2">
					{#if allRules.length > 0}
						<div class="relative">
							<Button variant="outline" class="gap-2" onclick={() => (showExportMenu = !showExportMenu)}>
								<Download class="h-4 w-4" />
								Export
							</Button>

							{#if showExportMenu}
								<!-- svelte-ignore a11y_click_events_have_key_events -->
								<!-- svelte-ignore a11y_no_static_element_interactions -->
								<div class="bg-popover border-border absolute right-0 z-10 mt-1 w-48 rounded-md border py-1 shadow-md">
									<button class="hover:bg-muted w-full px-4 py-2 text-left text-sm" onclick={() => handleExport('yaml', 'imported')}>Imported Rules (YAML)</button>
									<button class="hover:bg-muted w-full px-4 py-2 text-left text-sm" onclick={() => handleExport('json', 'imported')}>Imported Rules (JSON)</button>
									<button class="hover:bg-muted w-full px-4 py-2 text-left text-sm" onclick={() => handleExport('yaml', 'all')}>All Rules (YAML)</button>
									<button class="hover:bg-muted w-full px-4 py-2 text-left text-sm" onclick={() => handleExport('json', 'all')}>All Rules (JSON)</button>
								</div>
								<!-- svelte-ignore a11y_click_events_have_key_events -->
								<!-- svelte-ignore a11y_no_static_element_interactions -->
								<div class="fixed inset-0 z-0" onclick={() => (showExportMenu = false)}></div>
							{/if}
						</div>

						{#if importedRules.length > 0}
							<Button variant="destructive" class="gap-2" onclick={handleClearImported}>
								<Trash2 class="h-4 w-4" />
								Clear Imported
							</Button>
						{/if}
					{/if}
				</div>
			</div>

			<!-- Filter tabs -->
			<Tabs bind:value={activeTab} class="mb-4">
				<TabsList>
					<TabsTrigger value="all">All ({allRules.length})</TabsTrigger>
					<TabsTrigger value="auto">Auto-Generated ({autoRules.length})</TabsTrigger>
					<TabsTrigger value="imported">Imported ({importedRules.length})</TabsTrigger>
					{#if engineRules.length > 0}
						<TabsTrigger value="engine">
							Engine ({engineRules.length})
							{#if engineLastRunLabel}<span class="ml-1.5 text-xs text-muted-foreground font-normal">{engineLastRunLabel}</span>{/if}
						</TabsTrigger>
					{/if}
				</TabsList>
			</Tabs>

			<!-- Filter bar -->
			<div class="mb-4 flex flex-wrap items-center gap-3">
				<!-- Search input -->
				<div class="relative min-w-[200px] flex-1">
					<Search class="text-muted-foreground absolute top-2.5 left-2.5 h-4 w-4" />
					<Input type="text" placeholder="Search rules..." bind:value={searchTerm} class="pl-9" />
				</div>

				<!-- Rule Type dropdown -->
				<DropdownMenu>
					<DropdownMenuTrigger>
						<Button variant="outline" size="sm" class="gap-1.5">
							Rule Type
							{#if selectedRuleTypes.size > 0}
								<Badge variant="secondary" class="ml-1">{selectedRuleTypes.size}</Badge>
							{/if}
						</Button>
					</DropdownMenuTrigger>
					<DropdownMenuContent>
						{#each uniqueRuleTypes as ruleType}
							<DropdownMenuCheckboxItem
								checked={selectedRuleTypes.has(ruleType)}
								onCheckedChange={() => selectedRuleTypes = toggleSetItem(selectedRuleTypes, ruleType)}
							>
								{ruleType}
							</DropdownMenuCheckboxItem>
						{/each}
					</DropdownMenuContent>
				</DropdownMenu>

				<!-- Domain dropdown -->
				<DropdownMenu>
					<DropdownMenuTrigger>
						<Button variant="outline" size="sm" class="gap-1.5">
							Domain
							{#if selectedDomains.size > 0}
								<Badge variant="secondary" class="ml-1">{selectedDomains.size}</Badge>
							{/if}
						</Button>
					</DropdownMenuTrigger>
					<DropdownMenuContent>
						{#each uniqueDomains as domain}
							<DropdownMenuCheckboxItem
								checked={selectedDomains.has(domain)}
								onCheckedChange={() => selectedDomains = toggleSetItem(selectedDomains, domain)}
							>
								{domain}
							</DropdownMenuCheckboxItem>
						{/each}
					</DropdownMenuContent>
				</DropdownMenu>

				<!-- Target Variable dropdown -->
				<DropdownMenu>
					<DropdownMenuTrigger>
						<Button variant="outline" size="sm" class="gap-1.5">
							Variable
							{#if selectedTargetVars.size > 0}
								<Badge variant="secondary" class="ml-1">{selectedTargetVars.size}</Badge>
							{/if}
						</Button>
					</DropdownMenuTrigger>
					<DropdownMenuContent class="max-h-64 overflow-y-auto">
						{#each uniqueTargetVars as variable}
							<DropdownMenuCheckboxItem
								checked={selectedTargetVars.has(variable)}
								onCheckedChange={() => selectedTargetVars = toggleSetItem(selectedTargetVars, variable)}
							>
								{variable}
							</DropdownMenuCheckboxItem>
						{/each}
					</DropdownMenuContent>
				</DropdownMenu>

				<!-- Violations toggle -->
				<Button
					variant={violationsOnly ? 'default' : 'outline'}
					size="sm"
					onclick={() => violationsOnly = !violationsOnly}
				>
					Issues Only
				</Button>

				<!-- Clear all (visible when filters active) -->
				{#if hasActiveFilters}
					<Button variant="ghost" size="sm" class="gap-1 text-muted-foreground" onclick={clearAllFilters}>
						<X class="h-3.5 w-3.5" />
						Clear
					</Button>
				{/if}
			</div>

			<!-- Result count when filtered -->
			{#if hasActiveFilters}
				<p class="text-muted-foreground mb-3 text-sm">
					Showing {displayedRules.length} of {tabFilteredRules.length} rules
				</p>
			{/if}

			<!-- Rules list -->
			{#if displayedRules.length === 0}
				<div class="flex flex-col items-center justify-center rounded-lg border-2 border-dashed py-16">
					<Upload class="text-muted-foreground mb-4 h-12 w-12" />
					{#if activeTab === 'imported'}
						<h3 class="text-foreground mb-2 text-lg font-semibold">No imported rules</h3>
						<p class="text-muted-foreground mb-4 max-w-sm text-center text-sm">
							Upload CDISC-compatible YAML rule files to add custom validation rules.
						</p>
					{:else if activeTab === 'auto'}
						<h3 class="text-foreground mb-2 text-lg font-semibold">No auto-generated rules</h3>
						<p class="text-muted-foreground mb-4 max-w-sm text-center text-sm">
							Load a Define-XML file alongside your datasets to auto-generate validation rules.
						</p>
					{:else if activeTab === 'engine'}
						<h3 class="text-foreground mb-2 text-lg font-semibold">No engine results</h3>
						<p class="text-muted-foreground mb-4 max-w-sm text-center text-sm">
							Upload dataset files (.xpt) to run CDISC engine validation.
						</p>
					{:else}
						<h3 class="text-foreground mb-2 text-lg font-semibold">No rules available</h3>
						<p class="text-muted-foreground mb-4 max-w-sm text-center text-sm">
							Upload YAML rule files or load a Define-XML to generate validation rules.
						</p>
					{/if}
				</div>
			{:else}
				<div class="space-y-3">
					{#each displayedRules as rule (rule.Core.Id)}
						{@const ruleViolations = violationsByRule.get(rule.Core.Id)}
						<Card>
							<CardHeader class="pb-3">
								<div class="flex items-start justify-between">
									<div class="flex-1">
										<CardTitle class="flex items-center gap-2 text-base">
											<code class="text-sm">{rule.Core.Id}</code>
											{#if getRuleSource(rule) === 'engine'}
												<Badge variant="secondary" class="border-amber-300 bg-amber-50 text-amber-800 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-300">Engine</Badge>
											{:else if isImported(rule)}
												<Badge variant="default">Imported</Badge>
											{:else}
												<Badge variant="outline">Auto</Badge>
											{/if}
											<Badge variant={getExecutabilityVariant(rule)}>
												{rule.Executability}
											</Badge>
											{#if ruleViolations}
												<Badge variant="destructive">
													{ruleViolations.totalIssues} {ruleViolations.totalIssues === 1 ? 'issue' : 'issues'}
												</Badge>
											{/if}
										</CardTitle>
									</div>
									<div class="flex items-center gap-1">
										{#if ruleViolations}
											<Button
												variant="ghost"
												size="sm"
												class="text-muted-foreground hover:text-foreground h-8 gap-1.5 px-2"
												onclick={() => handleViewViolations(rule.Core.Id)}
												title="View violations in dataset"
											>
												<Eye class="h-4 w-4" />
												<span class="text-xs">View</span>
											</Button>
										{/if}
										{#if isImported(rule)}
											<Button
												variant="ghost"
												size="sm"
												class="text-muted-foreground hover:text-destructive h-8 w-8 p-0"
												onclick={() => handleDelete(rule.Core.Id)}
											>
												<Trash2 class="h-4 w-4" />
											</Button>
										{/if}
									</div>
								</div>
							</CardHeader>
							<CardContent class="pt-0">
								<p class="text-foreground mb-3 text-sm">{rule.Description}</p>
								<div class="flex flex-wrap gap-2">
									<Badge variant="outline">{rule.Rule_Type}</Badge>
									{#if rule.Target_Variable}
										<Badge variant="secondary">Target: {rule.Target_Variable}</Badge>
									{/if}
									<Badge variant="secondary">Scope: {getScopeDisplay(rule)}</Badge>
									<Badge variant="outline">Sensitivity: {rule.Sensitivity}</Badge>
									{#if ruleViolations}
										<Badge variant="outline">
											{ruleViolations.datasets.length} {ruleViolations.datasets.length === 1 ? 'dataset' : 'datasets'} affected
										</Badge>
									{/if}
								</div>
							</CardContent>
						</Card>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>
